version: '3'
services:
  app:
    image: leopalazzi/realisation-handler-front:realisation-handler-front
    ports:
      - 80:80
    networks:
      - web
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - web
networks:
  web:
    driver: bridge