export const projectsConfig = [
  // Les Projets //
  // FILTRES // image, etalonnage, realisation, réalisation // photographie, numerique, pellicule, // clip, documentaire, fiction,  //

  {
    id: 1,
    projectTitle: "Adomination",
    projectYear: 2023,
    projectDirector: "Camille Degeye",
    projectProducer: "Cultural Workers & Petit Chaos",
    camera: "Super16",
    projectDuration: "12'",
    photographerName: "Robin Fresson",
    videoLink: "",
    projectDirectory: "SCREENSHOTSADOMINATION",
    filters: ["etalonnage", "clip", "pellicule"],
    nomination: "Côté court, Pantin",
    imageWidth: "1280px",
    imageHeight: "960px",
  },
  {
    id: 2,
    projectTitle: "ÆON",
    projectYear: 2020,
    projectDirector: "Emmanuel Fraisse",
    projectProducer: "Caïmans Production",
    camera: "Panasonic GH5 & Drone",
    projectDuration: "30’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "https://vimeo.com/483612628/fb9311366c",
    projectDirectory: "SCREENSHOTSAEON",
    filters: ["etalonnage", "realisation", "image", "fiction", "numerique"],
    nomination:
      "Rhode Island International Film Festival - Grand Prix du meilleur film expérimental / Beijing International Film Festival / Festival International Signes de Nuit, Paris Mention for the night Award / Chéries-Chéris, Paris / Bogòta Experimental Film Festival - Competition Poetic Dweling",
    imageWidth: "1793px",
    imageHeight: "1080px",
  },
  {
    id: 3,
    projectTitle: "AFTER",
    projectYear: 2023,
    projectDirector: "Anthony Lapia",
    projectProducer: "Société Acéphale",
    camera: "Super16 & HD",
    projectDuration: "70’",
    photographerName: "Robin Fresson & Raimon Gaffier",
    videoLink: "",
    projectDirectory: "SCREENSHOTSAFTER",
    filters: ["etalonnage", "fiction", "pellicule"],
    nomination: "Berlinale (Panorama), IndieLisboa",
    imageWidth: "1796px",
    imageHeight: "1080px",
  },
  {
    id: 4,
    projectTitle: "Bibimbap",
    projectYear: 2019,
    projectDirector: "Guilhem Amesland",
    projectProducer: "Caïmans Production",
    camera: "Sony F55 RAW",
    projectDuration: "20’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSBIBIMBAP",
    filters: ["etalonnage", "image", "fiction", "numerique"],
    nomination: "Third Price Oblique Mecal Pro, Mecal Barcelone",
    imageWidth: "1920px",
    imageHeight: "1080px",
  },
  {
    id: 5,
    projectTitle: "Bloom",
    projectYear: 2018,
    projectDirector: "Emmanuel Fraisse",
    projectProducer: "La Fémis",
    camera: "Sony F5 RAW",
    projectDuration: "19’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSBLOOM",
    filters: ["etalonnage", "realisation", "image", "fiction", "numerique"],
    nomination: "",
    imageWidth: "1887px",
    imageHeight: "920px",
  },
  {
    id: 6,
    projectTitle: "Bosphore",
    projectYear: 2018,
    projectDirector: "Raphaël Duracell",
    projectProducer: "",
    camera: "Sony F55 RAW",
    projectDuration: "",
    photographerName: "Emmanuel Fraisse",
    videoLink: "https://www.youtube.com/watch?v=Wkvvf7b43gc",
    projectDirectory: "SCREENSHOTSBOSPHORE",
    filters: ["etalonnage", "image", "clip", "numerique"],
    nomination: "",
    imageWidth: "3360px",
    imageHeight: "1874px",
  },
  {
    id: 7,
    projectTitle: "Caillou",
    projectYear: 2021,
    projectDirector: "Mathilde Poymiro",
    projectProducer: "Barberousse Films",
    camera: "",
    projectDuration: "25’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSCAILLOU",
    filters: ["etalonnage", "image", "fiction", "numerique"],
    nomination:
      "Côté court, Pantin - compétition nationale / Premiers Plans, Angers Prix des jeunes internationaux, Prix des bibliothécaires, Prix d'interprétation",
    imageWidth: "1920px",
    imageHeight: "1080px",
  },
  {
    id: 8,
    projectTitle: "Dans La Nuit Les Enfants",
    projectYear: 2022,
    projectDirector: "Jeanne Mayer",
    projectProducer: "Mabel Films",
    camera: "Sony FS7",
    projectDuration: "20’",
    photographerName: "Juliette Barrat",
    videoLink: "",
    projectDirectory: "SCREENSHOTSDANSLANUITLESENFANTS",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "",
    imageWidth: "1998px",
    imageHeight: "1080px",
  },
  {
    id: 9,
    projectTitle: "Elancourt Mambo",
    projectYear: 2023,
    projectDirector: "Romain André",
    projectProducer: "Mabel Films",
    camera: "Alexa mini",
    projectDuration: "22’",
    photographerName: "Manuel Bolaños",
    videoLink: "",
    projectDirectory: "SCREENSHOTSELANCOURTMAMBO",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "",
    imageWidth: "3840px",
    imageHeight: "2160px",
  },
  {
    id: 10,
    projectTitle: "En Chien",
    projectYear: 2021,
    projectDirector: "Axel Würsten",
    projectProducer: "Phénomènes Films",
    camera: "Super 16",
    projectDuration: "",
    photographerName: "Emmanuel Fraisse",
    videoLink: "https://www.youtube.com/watch?v=YkGzsfW0LS8",
    projectDirectory: "SCREENSHOTSENCHIEN",
    filters: ["etalonnage", "image", "fiction", "pellicule"],
    nomination: "",
    imageWidth: "1849px",
    imageHeight: "1390px",
  },
  {
    id: 11,
    projectTitle: "L’Enfant au Diamant",
    projectYear: 2022,
    projectDirector: "Pierre-Edouard Dumora",
    projectProducer: "Les Films du Worso & Melodrama",
    camera: "Super16 & 35mm",
    projectDuration: "30’",
    photographerName: "Ville Piippo",
    videoLink: "",
    projectDirectory: "SCREENSHOTSENFANTAUDIAMANT",
    filters: ["etalonnage", "fiction", "pellicule"],
    nomination: "Locarno",
    imageWidth: "2047px",
    imageHeight: "849px",
  },
  {
    id: 12,
    projectTitle: "Fragment de drame",
    projectYear: 2018,
    projectDirector: "L.Garcia",
    projectProducer: "La Fémis",
    camera: "Super16",
    projectDuration: "24’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSFRAGMENTDEDRAME",
    filters: ["image", "fiction", "pellicule"],
    nomination:
      "Cinéfondation, Festival de Cannes / L’Étrange Festival, Paris / Festival du film méditerranéen, Tanger / Denver Film Festival, USA",
    imageWidth: "1000px",
    imageHeight: "750px",
  },
  {
    id: 13,
    projectTitle: "Fraya",
    projectYear: 2022,
    projectDirector: "Clémentine Delbecq",
    projectProducer: "Alta Rocca Films",
    camera: "Arri Amira",
    projectDuration: "25’",
    photographerName: " Pauline Doméjean",
    videoLink: "",
    projectDirectory: "SCREENSHOTSFRAYA",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "Côté court, Pantin",
    imageWidth: "1998px",
    imageHeight: "1080px",
  },
  {
    id: 14,
    projectTitle: "Idiot Fish",
    projectYear: 2022,
    projectDirector: "Hakim Mao",
    projectProducer: "Bobilux & Capricci",
    camera: "Alexa mini",
    projectDuration: "25’",
    photographerName: "François Ray",
    videoLink: "",
    projectDirectory: "SCREENSHOTSIDIOTFISH",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "FIFIB Lauréat Film Workout / Diffusé sur Arte",
    imageWidth: "3200px",
    imageHeight: "1800px",
  },
  {
    id: 15,
    projectTitle: "Insieme Insieme",
    projectYear: 2022,
    projectDirector: "Bernardo Zanotta",
    projectProducer: "Venin Films",
    camera: "Super16",
    projectDuration: "37’",
    photographerName: "Ville Piippo",
    videoLink: "",
    projectDirectory: "SCREENSHOTSINSIEMEINSIEME",
    filters: ["etalonnage", "fiction", "pellicule"],
    nomination: "FID, Marseille",
    imageWidth: "1023px",
    imageHeight: "629px",
  },
  {
    id: 16,
    projectTitle: "La Petite Constantine,",
    projectYear: 2018,
    projectDirector: "Simon Serna",
    projectProducer: "La Fémis",
    camera: "Sony F5 RAW",
    projectDuration: "16’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSLAPETITECONSTANTINE",
    filters: ["etalonnage", "image", "fiction", "numerique"],
    nomination: "",
    imageWidth: "3150px",
    imageHeight: "1898px",
  },
  {
    id: 17,
    projectTitle: "La Vedova Nera",
    projectYear: 2023,
    projectDirector: "River & Jack McKinnon",
    projectProducer: "Melodrama",
    camera: "Arri Amira",
    projectDuration: "20’",
    photographerName: "Maxime Berger",
    videoLink: "",
    projectDirectory: "SCREENSHOTSLAVEDOVANERA",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "",
    imageWidth: "3840px",
    imageHeight: "2160px",
  },
  {
    id: 18,
    projectTitle: "Lit de punaise",
    projectYear: 2019,
    projectDirector: "Axel Würsten",
    projectProducer: "La Femis, Arte, Caïmans production",
    camera: "Sony F55 RAW",
    projectDuration: "",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSLITDEPUNAISE",
    filters: ["etalonnage", "image", "fiction", "numerique"],
    nomination: "",
    imageWidth: "3360px",
    imageHeight: "1816px",
  },
  {
    id: 19,
    projectTitle: "Loon / Orange",
    projectYear: 2023,
    projectDirector: "Jules Cassignol",
    projectProducer: "Premier Cri Production",
    camera: "Sony FX6",
    projectDuration: "",
    photographerName: "Pauline Doméjean",
    videoLink: "",
    projectDirectory: "SCREENSHOTSLOON",
    filters: ["etalonnage", "clip", "numerique"],
    nomination: "",
    imageWidth: "3840px",
    imageHeight: "2160px",
  },
  {
    id: 20,
    projectTitle: "Mémoires du Bois",
    projectYear: 2023,
    projectDirector: "Théo Vincent",
    projectProducer: "le G.R.E.C ",
    camera: " Red Dragon",
    projectDuration: "20’",
    photographerName: "Léo Roussel",
    videoLink: "",
    projectDirectory: "SCREENSHOTSMEMOIRESDUBOIS",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "",
    imageWidth: "3585px",
    imageHeight: "2160px",
  },
  {
    id: 21,
    projectTitle: "Memory Slot",
    projectYear: 2023,
    projectDirector: "Yann Gonzalès",
    projectProducer: "Venin Films & Le Fresnoy",
    camera: "super16",
    projectDuration: "12’",
    photographerName: " Manuel Bolaños",
    videoLink: "",
    projectDirectory: "SCREENSHOTSMEMORYSLOT",
    filters: ["etalonnage", "fiction", "pellicule"],
    nomination: "Sexpérimentaux, Cinémathèque française",
    imageWidth: "2048px",
    imageHeight: "1556px",
  },
  {
    id: 22,
    projectTitle: "Millions of Memories",
    projectYear: 2018,
    projectDirector: "Laura Rius Aran",
    projectProducer: "La Fémis",
    camera: "",
    projectDuration: "25’",
    photographerName: "",
    videoLink: "",
    projectDirectory: "SCREENSHOTSMILLIONSMILLIONSOFMEMORIES",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination:
      "FILMADRID International Film Festival - Premio Openecam mejor Pelìcula",
    imageWidth: "3360px",
    imageHeight: "1894px",
  },
  {
    id: 23,
    projectTitle: "Mono No Aware",
    projectYear: 2018,
    projectDirector: "Raphaël Duracell",
    projectProducer: "La Fémis",
    camera: "Sony F5 RAW",
    projectDuration: "22’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSMONONOAWARE",
    filters: ["etalonnage", "image", "fiction", "numerique"],
    nomination:
      "Côté court, Pantin, Mention spéciale du jury / 7e lune, Lune d’Or",
    imageWidth: "1720px",
    imageHeight: "1080px",
  },
  {
    id: 24,
    projectTitle: "Preparadise Sorry Now",
    projectYear: 2023,
    projectDirector: "Douna Lim & Théo Pessos",
    projectProducer: "Glassbox",
    camera: "HDV",
    projectDuration: "60’",
    photographerName: "",
    videoLink: "",
    projectDirectory: "SCREENSHOTSPREPARADISESORRYNOW",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "",
    imageWidth: "1920px",
    imageHeight: "1080px",
  },
  {
    id: 25,
    projectTitle: "Rayon Frais",
    projectYear: 2023,
    projectDirector: "Karina Ykrelef",
    projectProducer: "Furyo Films",
    camera: "Alexa mini",
    projectDuration: "20’",
    photographerName: "Julien Guillery",
    videoLink: "",
    projectDirectory: "SCREENSHOTSRAYONFRAIS",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "",
    imageWidth: "3996px",
    imageHeight: "2160px",
  },
  {
    id: 26,
    projectTitle: "Rouge amoureuse",
    projectYear: 2018,
    projectDirector: "L.Garcia",
    projectProducer: "Parsifal films",
    camera: "",
    projectDuration: "24’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSROUGEAMOUREUSE",
    filters: ["image", "etalonnage", "fiction", "numerique"],
    nomination: "Entrevues, Belfort, Prix CAMIRA/ Chéries-Chéris, Paris",
    imageWidth: "968px",
    imageHeight: "726px",
  },
  {
    id: 27,
    projectTitle: "Salut les Zins",
    projectYear: 2023,
    projectDirector: "Paul Nouhet",
    projectProducer: "Les Films du Sursaut",
    camera: "Sony FX6",
    projectDuration: "45’",
    photographerName: "Pauline Doméjean",
    videoLink: "",
    projectDirectory: "SCREENSHOTSSALUTLESZINS",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "",
    imageWidth: "3224px",
    imageHeight: "2160px",
  },
  {
    id: 28,
    projectTitle: "ST4R",
    projectYear: 2022,
    projectDirector: "Julia Tarissan",
    projectProducer: "Le Fresnoy",
    camera: "Alexa mini",
    projectDuration: "20’",
    photographerName: "Lucie Ternisien",
    videoLink: "",
    projectDirectory: "SCREENSHOTST4R",
    filters: ["etalonnage", "fiction", "numerique"],
    nomination: "",
    imageWidth: "XXXXXXXXXXXX",
    imageHeight: "XXXXXXXXXXX",
  },
  {
    id: 29,
    projectTitle: "Allerseelen",
    projectYear: 2023,
    projectDirector: "Benjamin Goubet",
    projectProducer: "Art Association & la HEAD",
    camera: "Sony A7SIII",
    projectDuration: "6’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSALLERSEELEN",
    filters: ["image", "etalonnage", "numerique", "clip"],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "960px",
  },
  {
    id: 30,
    projectTitle: "Vers le nord",
    projectYear: 2023,
    projectDirector: "Pauline Penichout ",
    projectProducer: "KIDAM & Fondation META",
    camera: "Panasonic GH5",
    projectDuration: "17’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSVERSLENORD",
    filters: ["image", "etalonnage", "numerique", "fiction"],
    nomination: "Côté court, Pantin",
    imageWidth: "1280px",
    imageHeight: "771px",
  },
  {
    id: 31,
    projectTitle: "Coconut Head Generation",
    projectYear: 2023,
    projectDirector: "Alain Kassenda",
    projectProducer: "Ajimati Films",
    camera: "",
    projectDuration: "90’",
    photographerName: "",
    videoLink: "",
    projectDirectory: "SCREENSHOTSCOCONUTHEADGENERATION",
    filters: ["etalonnage", "numerique", "fiction"],
    nomination:
      "Cinéma du Réel, compétition nationale – Grand Prix / IDFA, Amsterdam",
    imageWidth: "1280px",
    imageHeight: "720px",
  },
  {
    id: 32,
    projectTitle: "Le jour commence au bord de la nuit",
    projectYear: 2022,
    projectDirector: "Lau Garcia",
    projectProducer: "Orphée films & Saison unique",
    camera: "Super16",
    projectDuration: "15’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSLEJOURCOMMENCEAUBORDDELANUIT",
    filters: ["image", "numerique", "fiction"],
    nomination: "Entrevues, Belfort / Oberhausen",
    imageWidth: "1280px",
    imageHeight: "960px",
  },
  {
    id: 33,
    projectTitle: "Carné.e.s",
    projectYear: 2021,
    projectDirector: "Léo Deschênes",
    projectProducer: "Les Films du Clan",
    camera: "Alexa mini",
    projectDuration: "25’",
    photographerName: "François Ray",
    videoLink: "",
    projectDirectory: "SCREENSHOTSCARNEES",
    filters: ["etalonnage", "numerique", "fiction"],
    nomination: "Clermont-Ferrand (programme Canal+)",
    imageWidth: "1280px",
    imageHeight: "720px",
  },
  {
    id: 34,
    projectTitle: "The Sound of Metamorphosis",
    projectYear: 2021,
    projectDirector: "Jules Cassignol (Jazzboy)",
    projectProducer: "",
    camera: "Sony F55 RAW",
    projectDuration: "17’",
    photographerName: "Till Leprêtre",
    videoLink: "",
    projectDirectory: "SCREENSHOTSTHESOUNDOFMETAMORPHOSIS",
    filters: ["etalonnage", "numerique", "fiction"],
    nomination: "FAME 2022, Gaîté Lyrique, Paris",
    imageWidth: "1280px",
    imageHeight: "768px",
  },
  {
    id: 35,
    projectTitle: "Super Nova",
    projectYear: 2020,
    projectDirector: "Juliette Saint-Sardos",
    projectProducer: "Dùne & Composite films",
    camera: "Super16",
    projectDuration: "15’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSSUPERNOVA",
    filters: ["image", "etalonnage", "pellicule", "fiction"],
    nomination: "Côté court, Pantin / Diffusé sur Arte",
    imageWidth: "1280px",
    imageHeight: "771px",
  },
  {
    id: 36,
    projectTitle: "Visuels de la tournée de -M- «Lettre infinie»",
    projectYear: 2019,
    projectDirector: "J.Frenkel & C.Castro",
    projectProducer: "La comète",
    camera: "RED Monstro 8K",
    projectDuration: "",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSVISUELSDELATOURNEEDEM",
    filters: ["image", "realisation", "etalonnage", "numerique", "fiction"],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "629px",
  },
  {
    id: 37,
    projectTitle: "ALPA",
    projectYear: 2021,
    projectDirector: "Paolo Mattei-Lvovsky",
    projectProducer: "Premier Souffle Production",
    camera: "Alexa mini",
    projectDuration: "23’",
    photographerName: "Ulysse Gilbert-Castel",
    videoLink: "",
    projectDirectory: "SCREENSHOTSALPA",
    filters: ["etalonnage", "numerique", "fiction"],
    nomination: "Festival international de court-métrage de São Paulo",
    imageWidth: "1280px",
    imageHeight: "544px",
  },
  {
    id: 38,
    projectTitle: "Anabase",
    projectYear: 2021,
    projectDirector: "Benjamin Goubet",
    projectProducer: "HEAD Genève",
    camera: "Sony A7SIII",
    projectDuration: "",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSANABASE",
    filters: ["image", "etalonnage", "numerique", "fiction"],
    nomination:
      "Côté court, Pantin / Winthertur / San Sebastian / Atlantis Best Cinematography",
    imageWidth: "1280px",
    imageHeight: "851px",
  },
  {
    id: 39,
    projectTitle: "The peacekeeper",
    projectYear: 2017,
    projectDirector: "Pierre Edouard Dumora",
    projectProducer: "XXXXXXXXXXXXXXXXXXX",
    camera: "Canon 5D",
    projectDuration: "19’",
    photographerName: "",
    videoLink: "",
    projectDirectory: "SCREENSHOTSPEACEKEEPER",
    filters: ["etalonnage", "numerique", "fiction"],
    nomination:
      "25 fps Zagreb festival (special mention critics award). Côté Court, Pantin. Le FID Marseille (section écrans parallèles - les sentiers)",
    imageWidth: "1280px",
    imageHeight: "719px",
  },
  {
    id: 40,
    projectTitle: "Uma Resistencia",
    projectYear: 2021,
    projectDirector: "Barbara Balestas Kazazian",
    projectProducer: "XXXXXXXXXXXXXXXXXXX",
    camera: "Varicam 35",
    projectDuration: "25’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSUMARESISTENCIA",
    filters: ["image", "etalonnage", "numerique", "fiction"],
    nomination: "DocLisboa, Lisbonne / Premiers plans, Angers",
    imageWidth: "1280px",
    imageHeight: "831px",
  },
  {
    id: 41,
    projectTitle: "Coeur à prendre",
    projectYear: 2018,
    projectDirector: "Clément Fourment",
    projectProducer: "La Fémis",
    camera: "Sony F65 & optiques Zeiss Master Prime",
    projectDuration: "24’",
    photographerName: "Clément Fourment",
    videoLink: "",
    projectDirectory: "SCREENSHOTSCOEURAPRENDRE",
    filters: ["numerique", "fiction"],
    nomination: "Go Shorts - Nimègue, Pays-Bas",
    imageWidth: "1280px",
    imageHeight: "771px",
  },
  {
    id: 42,
    projectTitle: "Galathea",
    projectYear: 2018,
    projectDirector: "Antonio Messana",
    projectProducer: "La Fémis",
    camera: "Sony F5",
    projectDuration: "12’",
    photographerName: "Clément Fourment",
    videoLink: "",
    projectDirectory: "SCREENSHOTSGALATHEA",
    filters: ["image", "etalonnage", "numerique", "fiction"],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "548px",
  },
  {
    id: 43,
    projectTitle: "Veilleurs",
    projectYear: 2018,
    projectDirector: "Victor Aureillian",
    projectProducer: "La Fémis",
    camera: "",
    projectDuration: "9'",
    photographerName: "",
    videoLink: "",
    projectDirectory: "SCREENSHOTSVEILLEURS",
    filters: ["etalonnage", "numerique", "fiction"],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "720px",
  },
  {
    id: 44,
    projectTitle: "Trace",
    projectYear: 2017,
    projectDirector: "Aliona Zagurovska-Demonsant",
    projectProducer: "La Fémis",
    camera: "Alexa XT & optiques Zeiss Master Prime",
    projectDuration: "24’",
    photographerName: "Réginald Galienne",
    videoLink: "",
    projectDirectory: "SCREENSHOTSTRACE",
    filters: ["image", "numerique", "fiction"],
    nomination: "FID campus - Marseille",
    imageWidth: "954px",
    imageHeight: "719px",
  },
  {
    id: 45,
    projectTitle: "Collège de Ouangani, Mayotte",
    projectYear: 2018,
    projectDirector: "Emmanuel Fraisse",
    projectProducer: "TERRENEUVE architectes",
    camera: "",
    projectDuration: "8'",
    photographerName: "Emmanuel Fraisse",
    videoLink: "https://vimeo.com/304568292",
    projectDirectory: "SCREENSHOTSCOLLEGEDEOUANGANI",
    filters: [
      "etalonnage",
      "image",
      "realisation",
      "documentaire",
      "numerique",
    ],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "721px",
  },
  {
    id: 46,
    projectTitle: "J'avais un camarade",
    projectYear: 2018,
    projectDirector: "Aurore Toulon",
    projectProducer: "La Fémis",
    camera: "Super16",
    projectDuration: "8'",
    photographerName: "Aurore Toulon",
    videoLink: "",
    projectDirectory: "SCREENSHOTSJAVAISUNCAMARADE",
    filters: ["pellicule", "fiction "],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "771px",
  },
  {
    id: 47,
    projectTitle: "Deadman walking on the moon",
    projectYear: 2018,
    projectDirector: "Julia Tarissan & Juliet Casella",
    projectProducer: "",
    camera: "Canon 5D MkII",
    projectDuration: "4'",
    photographerName: "",
    videoLink: "",
    projectDirectory: "SCREENSHOTSDEADMANWALKINGONTHEMOON",
    filters: ["etalonnage", "clip", "numerique"],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "712px",
  },
  {
    id: 48,
    projectTitle: "Madeleine",
    projectYear: 2018,
    projectDirector: "Chloé Cortella",
    projectProducer: "Melocoton",
    camera: "",
    projectDuration: "16'",
    photographerName: "",
    videoLink: "",
    projectDirectory: "SCREENSHOTS MADELEINE",
    filters: ["etalonnage", "numerique", "fiction"],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "675px",
  },
  {
    id: 49,
    projectTitle: "Capitaine France",
    projectYear: 2018,
    projectDirector: "Thomas Robineau & Julien Paillet",
    projectProducer: "La Fémis",
    camera: "Archives",
    projectDuration: "21’",
    photographerName: "",
    videoLink: "XXXXXXXXXXXXXXXXXXX",
    projectDirectory: "SCREENSHOTSCAPITAINEFRANCE",
    filters: ["etalonnage", "numerique", "fiction"],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "692px",
  },
  {
    id: 50,
    projectTitle: "Britney on LSD",
    projectYear: 2018,
    projectDirector: "Elliot Totzauer",
    projectProducer: "Croche",
    camera: "",
    projectDuration: "4’",
    photographerName: "Emmanuel Fraisse",
    videoLink: "",
    projectDirectory: "SCREENSHOTSBRITNEYONLSD",
    filters: ["image, etalonnage, clip, numerique,"],
    nomination: "",
    imageWidth: "1280px",
    imageHeight: "960px",
  },

  // Les Photos //

  {
    id: 101,
    projectTitle: "Petite Terre, Mayotte",
    projectYear: 2018,
    projectDirectory: "PHOTOGRAPHIEPETITETERRE",
    filters: ["photographie"],
  },
  {
    id: 102,
    projectTitle: "L'île de la Réunion",
    projectYear: 2014,
    projectDirectory: "PHOTOGRAPHIELAREUNION",
    filters: ["photographie"],
    imageWidth: "1280px",
    imageHeight: "854px",
  },
  {
    id: 103,
    projectTitle: "Richmond, USA",
    projectYear: 2019,
    projectDirectory: "PHOTOGRAPHIERICHMOND",
    filters: ["photographie"],
  },
  {
    id: 104,
    projectTitle: "Pôle d’Excellence rurale de Chiconi, Mayotte",
    projectYear: 2018,
    projectDirectory: "PHOTOGRAPHIECHICONI",
    filters: ["photographie"],
  },
  {
    id: 105,
    projectTitle: "Liban",
    projectYear: 2018,
    projectDirectory: "PHOTOGRAPHIELIBAN",
    filters: ["photographie"],
  },
  {
    id: 106,
    projectTitle: "Liban 2",
    projectYear: 2019,
    projectDirectory: "PHOTOGRAPHIELIBAN2",
    filters: ["photographie"],
  },
];
